import Head from "next/head";
import {
  Box,
  Container,
  Typography,
  Link,
} from "@mui/material";
import { DataGrid, GridColDef } from "@mui/x-data-grid";
import { AcUnit } from "@mui/icons-material";
import { UserData } from "@/data/UserDataJson";

const columns: GridColDef[] = [
  {
    field: "id",
    headerName: "ID",
    width: 150,
    editable: false,
  },
  {
    field: "firstName",
    headerName: "First name",
    width: 150,
    editable: true,
  },
  {
    field: "lastName",
    headerName: "Last name",
    width: 150,
    editable: true,
  },
  {
    field: "jobTitle",
    headerName: "Job title",
    description: "This column has a value getter and is not sortable.",
    sortable: false,
    width: 160,
  },
];

export default function Home() {

  return (
    <Box>
      <Head>
        <title>Employee Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Box
          display="flex"
          alignItems="center"
          flexDirection="column"
          pt={4}
          pb={3}
        >
          <Typography variant="h4" component="h1" fontWeight={600} pb={2}>
            Employee Management
          </Typography>
          <Typography variant="body1">
            Made with <AcUnit /> in Minneapolis by{" "}
            <Link
              href={"https://github.com/wil-gerard"}
              target="_blank"
              rel="noopener noreferrer"
            >
              Wil Gerard
            </Link>
          </Typography>
        </Box>
        <Box style={{ height: 400, width: '100%' }}>
          <DataGrid
            rows={UserData.people}
            getRowId={(row) => row.id}
            columns={columns}
            pageSize={5}
            rowsPerPageOptions={[5]}
            checkboxSelection
          />
        </Box>
      </Container>
    </Box>
  );
}
